before_script:
  - apt update
  - apt install maven

build:
  stage: build
  script:
    - cd ./homework_11_CI_CD/
    - mvn compile

test:
  stage: test
  script:
    - cd ./homework_11_CI_CD/
    - mvn test