before_script:
  - apt-get update
  - apt-get install openjdk-8-jdk
  - java -version
  - apt-get install maven
  - maven -version

build:
  stage: build
  script:
    - cd ./homework_11_CI_CD/
    - mvn compile

test:
  stage: test
  script:
    - cd ./homework_11_CI_CD/
    - mvn test